# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('marvel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('issue_number', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('isbn', models.CharField(max_length=50, null=True)),
                ('page_count', models.IntegerField(null=True)),
                ('url', models.URLField(max_length=255)),
                ('series', models.IntegerField()),
                ('purchase', models.URLField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField()),
                ('characters', models.ManyToManyField(related_name='comics', to='questions.Character')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('comics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='m_comics.Comic')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readinglist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
