# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ('read',)},
        ),
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comic',
            name='issue_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comic',
            name='purchase',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='purchase_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comic',
            name='series',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
