# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='_format',
            field=models.CharField(default=b'', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='page_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='series',
            field=models.CharField(default=b'', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='comic',
            name='upc',
            field=models.CharField(default=b'', max_length=50, null=True),
        ),
    ]
