# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='read',
        ),
    ]
