# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m_comics', '0002_auto_20160504_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='comics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='m_comics.Comic'),
        ),
    ]
