# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_comics', '0003_auto_20160504_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={},
        ),
    ]
