# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_comics', '0004_auto_20160505_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
