# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_comics', '0005_auto_20160505_2013'),
        ('m_comics', '0002_remove_comic_read'),
    ]

    operations = [
    ]
