# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_comics', '0005_auto_20160504_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='comics',
            field=models.ManyToManyField(related_name='lists', to='m_comics.Comic'),
        ),
    ]
