# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_comics', '0006_auto_20160504_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='url',
            new_name='detail_url',
        ),
        migrations.RenameField(
            model_name='comic',
            old_name='purchase',
            new_name='purchase_url',
        ),
        migrations.RenameField(
            model_name='comic',
            old_name='isbn',
            new_name='upc',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='comic',
            name='_format',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='puchase_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='str_pur_date',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='comic',
            name='series',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
