# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvelprofile',
            name='fav_hero',
            field=models.CharField(default='', max_length=100),
        ),
    ]
