# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('name', models.CharField(blank=True, max_length=60)),
                ('real_name', models.CharField(blank=True, max_length=100)),
                ('marvel_name', models.CharField(blank=True, max_length=100)),
                ('marvel_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('thumbnail', models.CharField(blank=True, max_length=250)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('pob', models.CharField(blank=True, max_length=200)),
                ('citizenship', models.CharField(blank=True, max_length=90)),
                ('powers', models.CharField(blank=True, max_length=200)),
                ('total_comics', models.IntegerField()),
                ('golden', models.NullBooleanField()),
                ('silver', models.NullBooleanField()),
                ('bronze', models.NullBooleanField()),
                ('dark', models.NullBooleanField()),
                ('modern', models.NullBooleanField()),
                ('hair', models.CharField(blank=True, max_length=30)),
                ('eyes', models.CharField(blank=True, max_length=30)),
                ('first_appearance', models.CharField(blank=True, max_length=60)),
                ('identity_status', models.CharField(blank=True, max_length=60)),
                ('aliases', models.CharField(blank=True, max_length=250)),
                ('weight', models.CharField(blank=True, max_length=60)),
                ('height', models.CharField(blank=True, max_length=60)),
                ('group_aff', models.CharField(blank=True, max_length=250)),
                ('paraphernalia', models.CharField(blank=True, max_length=250)),
                ('education', models.CharField(blank=True, max_length=60)),
                ('occupation', models.CharField(blank=True, max_length=250)),
                ('abilities', models.CharField(blank=True, max_length=250)),
                ('weapons', models.CharField(blank=True, max_length=250)),
                ('origin', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
