# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20160503_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='eyes',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
