# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20160503_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='abilities',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='character',
            name='paraphernalia',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='character',
            name='powers',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
