# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20160503_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='citizenship',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
