# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20160503_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='education',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
