# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20160503_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='occupation',
            field=models.CharField(blank=True, max_length=6000),
        ),
    ]
