# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20160504_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bronze',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='dark',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='golden',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='modern',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='silver',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='total_comics',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
